### ISSUE TITLE
Compilation fails when the name of the source file has dash in it.

### ISSUE THREAD

**Issue by iss000** [Oric4ever/lcc6502#9]
Compilation fails when the name of the source file has dash in it.
The generated assembler is produced with invalid labels.
Example: if the source file is named 'type-sizes.c' the in asm source is:
```
Ltype-sizes129
	.word 1
Ltype-sizes130
	.word 1
Ltype-sizes131
	.word 2
Ltype-sizes132
	.word 2
Ltype-sizes134
	ldx #6 
 lda #2 
 jsr enter 
```
**Euphoric**: It's easy to fix, right? ;)

**Comment by Euphoric** [comment]
I don't understand why I was notified, as I have nothing to do with this project.

**Comment by iss000** [comment]
> I don't understand why I was notified, as I have nothing to do with this project.

'Euphoric' is the famous emulator for **Oric** written by the author of this project @**Oric4ever** and he used the alias 'Euphoric' since decades.

**Comment by iss000** [comment]
Actually there is no problem with the compiler but the bad -N parameter used. Sorry. Issue closed.
